sudo: required
services:
  - docker

language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew build
  - ./gradlew uT  --stacktrace --info
