version: '2.1' # version 2 is intentional, 3 is aimed at swarm and doesn't allow us to set mem-limits

services:
  postgres:
    image: postgres:9.5.8-alpine
    ports:
      - "5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: password
    volumes:
        - ./docker/initdb/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  app:
    image: favbuild:${TAG}
    entrypoint: "sh -c '/wait_for.sh -t 10 postgres:5432 -- java -Xms${APP_HEAP} -Xmx${APP_HEAP} -Djava.security.egd=file:/dev/./urandom -jar /app.jar'"
    depends_on:
      - "postgres"
    ports:
      - "${APP_PORT}"
    stop_signal: KILL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/info"]
      interval: 1s
      timeout: 1s
      retries: 1
    environment:
      SPRING_JPA_HIBERNATE_DDL-AUTO: create-drop
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/foo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: ${APP_PORT}
    volumes:
      - ./docker/wait_for.sh:/wait_for.sh
